displayName=Cox Grind
author=Discojanne
description=Store and visualize Chambers of Xeric raid data. View live splits, compare them to your average or target times, and see statistics for points, items, and purples.
tags=cox,chambers,xeric,raids,analytics
plugins=com.coxgrind.CoxGrindPlugin
version=1.0.0
